# Irrigation System Efficiency Configuration
# Efficiency values represent the fraction of applied water that reaches the crop root zone

irrigation_systems:
  Drip:
    efficiency: 0.90
    description: "Drip/trickle irrigation - localized, high efficiency"
    typical_application_rate: "2-4 mm/hr"
    
  Sprinkler:
    efficiency: 0.75
    description: "Sprinkler irrigation - overhead application"
    typical_application_rate: "5-15 mm/hr"
    
  Traditional:
    efficiency: 0.60
    description: "Traditional surface irrigation - furrow/border"
    typical_application_rate: "Variable"
    
  Flooded:
    efficiency: 0.60
    description: "Flood/basin irrigation - surface flooding"
    typical_application_rate: "Variable"
    
  Rainfed:
    efficiency: 1.00
    description: "No irrigation - rainfed agriculture"
    typical_application_rate: "N/A"
    
  Micro-sprinkler:
    efficiency: 0.85
    description: "Micro-sprinkler - localized overhead"
    typical_application_rate: "3-8 mm/hr"
    
  Center-pivot:
    efficiency: 0.80
    description: "Center pivot sprinkler system"
    typical_application_rate: "10-20 mm/hr"
    
  Surface:
    efficiency: 0.60
    description: "General surface irrigation"
    typical_application_rate: "Variable"
    
  Furrow:
    efficiency: 0.60
    description: "Furrow irrigation"
    typical_application_rate: "Variable"
    
  Border:
    efficiency: 0.65
    description: "Border irrigation"
    typical_application_rate: "Variable"
    
  Basin:
    efficiency: 0.70
    description: "Basin irrigation"
    typical_application_rate: "Variable"

# Efficiency adjustment factors for different conditions
adjustment_factors:
  well_maintained:
    multiplier: 1.0
    description: "System is well maintained and operated"
    
  poor_maintenance:
    multiplier: 0.85
    description: "System has poor maintenance"
    
  windy_conditions:
    sprinkler_reduction: 0.10
    description: "Wind reduces sprinkler efficiency by ~10%"
    
  high_evaporation:
    surface_reduction: 0.05
    description: "High evaporation reduces surface irrigation efficiency"
